/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class App{
        fun getSaludo(name : String, description : String) : String {
            return "Hello $name!, $description"
        }
}

fun main() {
    val app = App()
    println(app.getSaludo("Harvey", "I'm your father"))
}
